### PR TITLE
lua scripting language

### PR DESCRIPTION
**Pull request by winchy82dev**
Adding Lua scripting language

### CODE REVIEW

**Comment by ericspring08** [comment]
Please place Lua alphabetically in README.md

**Comment by winchy82dev** [comment]
> Please place Lua alphabetically in README.md
Done, thanks

**Comment by ericspring08** [comment]
Thanks for contributing!

**Comment by winchy82dev** [comment]
> Thanks for contributing!

you're welcome, my pleasure!

**Pull request merged**
