### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by itsOmSarraf**
Added, C++ to README.md along with its description alphabetically.

### CODE REVIEW

**Comment by ericspring08** [comment]
Thank you for contributing!

**Comment by itsOmSarraf** [comment]
> Thank you for contributing!

so I am a contributor now, for this repo?

**Comment by ericspring08** [comment]
> > Thank you for contributing!
> 
> so I am a contributor now, for this repo?
> 
> 

Yes, you are now a contributor.

**Comment by itsOmSarraf** [comment]
okay :) 

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Efficient

**Comment by ericspring08** [comment]
> okay :)
> 
> __ [sema-logo](https://semasoftware.com/gh) [ sema-logo ](https://semasoftware.com/gh) [ ](https://semasoftware.com/gh)  **Summary:** 👌 This code looks good  |  **Tags:** Efficient

You are now listed as a contributor in [CONTRIBUTORS.md](https://github.com/ericspring08/Awesome-Programming-Languages/blob/main/CONTRIBUTORS.md).

**Comment by itsOmSarraf** [comment]
yes checked thanks a lot :) 

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Pull request merged**
